FROM mhart/alpine-node:7.9.0

RUN apk add --no-cache \
    build-base \
    g++ \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    bash
    # imagemagick

RUN mkdir -p /home/app/web
WORKDIR /home/app/web

RUN yarn global add pm2@2.7.0 snyk
RUN snyk auth $SNYK_TOKEN

COPY package.json yarn.lock .snyk gulpfile.babel.js .babelrc ./

RUN yarn
RUN yarn run build
COPY . .

ENV PORT 3000

CMD ["pm2-docker", "start", "dist/app.js"]

EXPOSE 3000
