# Previously 7.9.0
FROM mhart/alpine-node:9.1.0

RUN apk add --no-cache \
    build-base \
    python

RUN mkdir -p /home/app/web
WORKDIR /home/app/web

RUN npm i -g yarn
RUN yarn global add pm2@2.7.0 snyk
RUN snyk auth $SNYK_TOKEN

COPY package.json yarn.lock .snyk gulpfile.babel.js .babelrc ./

RUN yarn
RUN yarn run build
COPY . .

ENV PORT 3000

CMD ["pm2-docker", "start", "dist/app.js"]

EXPOSE 3000
